name: Update Public and Beta Configs

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Python script to generate config files
        run: python categorize_all_protocols.py

      # === مراحل جدید برای تست سرعت ===
      - name: Download and Unzip Xray-core
        run: |
          curl -L -o xray.zip https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip
          unzip xray.zip xray
          chmod +x xray
          
      - name: Run Speed Test Script
        run: python speed_tester.py
      # =================================

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit and push to beta branch
        run: |
          git checkout -B beta
          git add .
          git commit -m "Update all configs and stats (with speedtest)" || echo "No changes to commit"
          git push -f origin beta

      - name: Prepare and push to main branch
        run: |
          git checkout main
          # فایل README.md را از برنچ بتا به برنچ main منتقل می‌کنیم
          git checkout beta -- README.md
          # فایل‌های ویژه را از برنچ main حذف می‌کنیم
          rm -rf protocols/vless protocols/vmess protocols/trojan protocols/special sub/protocols/vless sub/protocols/vmess sub/protocols/trojan sub/special
          # فایل تست شده را نیز حذف می‌کنیم
          rm -f sub/tested_configs.txt
          echo "Special and tested files removed for main branch."
          git add .
          git commit -m "Update public configs and stats" || echo "No changes to commit"
          git push origin main
