name: Update Public and Beta Configs

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  # === جاب اول: ساخت تمام فایل‌ها و آپدیت برنچ بتا ===
  build_and_update_beta:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Python script to generate all files
        run: python categorize_all_protocols.py

      - name: Commit all files to the beta branch
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Update all configs (incl. special vless)" || echo "No changes to commit"
          git push -f origin HEAD:beta

      - name: Upload all generated files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: all-configs
          path: .
          retention-days: 1

  # === جاب دوم: حذف فایل‌های ویژه و آپدیت برنچ عمومی ===
  update_main_branch:
    runs-on: ubuntu-latest
    needs: build_and_update_beta
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Download all generated files
        uses: actions/download-artifact@v4
        with:
          name: all-configs

      - name: Remove special folders
        run: |
          rm -rf protocols/vless
          rm -rf sub/vless
          echo "Special vless folders removed for main branch."
      
      - name: Commit and push public files to main branch
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit to main branch."
          else
            git commit -m "Update public configs"
            git push origin main
          fi
