name: 2. Speed Test Collected Configs

on:
  workflow_run:
    workflows: ["1. Collect and Categorize Configs"] # نام دقیق گردش کار اول
    types:
      - completed

jobs:
  test_and_commit:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download and prepare LiteSpeedTest
        run: |
          wget https://github.com/xxf098/LiteSpeedTest/releases/download/v0.14.1/lite-linux-amd64-v0.14.1.gz
          gunzip lite-linux-amd64-v0.14.1.gz
          chmod +x lite-linux-amd64-v0.14.1
      
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      # === مرحله جدید: ایجاد یک زیرمجموعه برای تست سریع ===
      - name: Prepare a small subset for testing
        run: |
          # خواندن 500 خط اول از فایل پورت 80 و ذخیره در یک فایل موقت
          head -n 500 ports/80.txt > ports/test_subset.txt
          echo "Created a test subset with the first 500 configs from port 80."

      # === مرحله ۱: تست اتصال و پینگ روی زیرمجموعه ===
      - name: Stage 1 - Test Connectivity (Ping)
        id: ping_test
        run: |
          echo "Testing connectivity of the subset..."
          # <<< تغییر جدید: تست فقط روی فایل زیرمجموعه >>>
          ./lite-linux-amd64-v0.14.1 -test ports/test_subset.txt -p 100 > ping_results.json 2>&1
          
          # فیلتر کردن کانفیگ‌های سالم و ذخیره در فایل جدید
          cat ping_results.json | jq -r 'select(.result.ok == true) | .link' > sub/ping_tested.txt

          echo "Ping test completed."

      # === مرحله ۲: تست سرعت کانفیگ‌های سالم ===
      - name: Stage 2 - Speed Test on Healthy Nodes
        run: |
          if [ -s sub/ping_tested.txt ]; then
            echo "Running speed test on nodes that passed the ping test..."
            ./lite-linux-amd64-v0.14.1 -test sub/ping_tested.txt -p 100 -speed > speed_results.json 2>&1
            
            # فیلتر کردن کانفیگ‌های پرسرعت و مرتب‌سازی بر اساس سرعت
            cat speed_results.json | jq -r 'select(.result.ok == true and .result.speed > 1.0) | .result.speed as $speed | .link as $link | {speed: $speed, link: $link}' | jq -s 'sort_by(.speed) | reverse | .[] | .link' > sub/tested_configs.txt
            
            echo "Speed test completed."
          else
            echo "No nodes passed the ping test. Skipping speed test."
            touch sub/tested_configs.txt
          fi

      - name: Commit and push tested configs
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          # حذف فایل‌های موقت قبل از کامیت
          rm -f ping_results.json speed_results.json sub/ping_tested.txt ports/test_subset.txt
          
          git add sub/tested_configs.txt
          if [ -s sub/tested_configs.txt ]; then
            git commit -m "Add/Update speed-tested configs (SUBSET TEST)" || echo "No changes to commit"
            git push
          else
            echo "No nodes passed the speed test. No commit needed."
          fi
